# Generated by Django 5.1.3 on 2024-11-29 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anilizor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documents',
            options={},
        ),
        migrations.AlterModelOptions(
            name='documentstext',
            options={},
        ),
    ]
