# Generated by Django 5.1.3 on 2024-11-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anilizor', '0003_cart_users_to_docs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_file', models.ImageField(upload_to='images/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
