# Generated by Django 5.1.3 on 2024-11-24 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anilizor', '0006_alter_docs_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users_to_docs',
            old_name='username',
            new_name='user',
        ),
    ]
